### ISSUE TITLE
Testimonials and Images

### ISSUE THREAD

**Issue by RyanNovas** [Empirical-org-Archive/Organization#166]
We have assets for these in this folder. 

https://drive.google.com/a/quill.org/folderview?id=0B2HguQEg6QQ1fmQxeDVyY3JXZHpSbUNzVThIZGdiWmpjYk9wS092cV9faE1vOTg0VnpCRG8&usp=sharing

Access it through Empirical Gmail or ask Ryan for permission as it includes personally identifiable information. We'll need to get permission from those who gave the quotes before posting them online.

**Comment by petergault** [comment]
Over the past two years, I have used Quill to teach my 7th and 8th grade special education English classes. Students are eager to use the program and are quick to celebrate getting a “green square”, denoting that they have passed an assigned skill.

Stephanie Wieland, KIPP DC Key Academy

The website is wonderful.  My students enjoy it and I like knowing they are getting some additional grammar practice, while improving their keyboarding skills.

Cheryl Green, Ahlf Junior High School 

QuillI is the best grammar tool for my students, and it teaches them how to closely read information. I appreciate the fact that students are required to check spelling and punctuation to score “green.”

Randall Carswell, Charlotte Mecklenburg Schools

@petergault since these are all going to be in quotes, I like we have to change "green square," to 'green square,' and "green." to 'green.'

**Comment by petergault** [comment]
http://www.cms.k12.nc.us/Pages/default.aspx
Randall's school where he taught before.

**Comment by petergault** [comment]
http://www.google.com/imgres?imgurl=http://www.kidfans.com/images/products/1146paw.jpg&imgrefurl=http://mcrae.searcyschools.org/?PageName%3DTeacherPage%26Page%3D1%26StaffID%3D143545&h=333&w=412&tbnid=7mzzUc0LKz76CM:&zoom=1&docid=TGFkl1khlljmjM&ei=RPrPVKPgH8v8sAS74IKYBw&tbm=isch&ved=0CHAQMyhFMEU

http://www.google.com/imgres?imgurl=http://www.searcy.com/phpThumb/phpThumb.php%253Fsrc%253D/files/newstaffy_images/newstaffy_nid_23771/2X3_crest_poster.jpg%2526zc%253D1&imgrefurl=http://www.searcy.com/dev/newstaffy/item/23771/Searcy%2BSchools%2BHolds%2BAnnual%2BReport%2Bto%2Bthe%2BPublic&h=2598&w=1734&tbnid=Fp6xF8fsSV0oOM:&zoom=1&docid=yxoFw0WHMzO5bM&itg=1&ei=RPrPVKPgH8v8sAS74IKYBw&tbm=isch&ved=0CCMQMygFMAU

Show the logo on the left hand side, show the name to the right.
