### ISSUE TITLE
Send 501(c)3 App to Google for free service

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#40]
Tell them we are a small nonprofit, it will take a year to get it approved. Can we please get free service? We're currently paying $40 a month to Google, that adds up!

**Comment by RyanNovas** [comment]
Done. However, I have low expectations. They are pretty cut and dry on the req's, and even require 501(c)3 status from organizations that are automatically exempt.

**Comment by matthewcoxatquill** [comment]
We need to re-open this issue. I just set everything up under the Hello email but we were rejected because the IRS hasn't added us to their searchable database. We can Check that here http://apps.irs.gov/app/eos/pub78Search.do?dispatchMethod=navigateSearch&pathName=forwardToPub78Search&searchChoice=pub78.

As soon as we show up there we should be able to immediately re-apply. The IRS claims they update this list monthly so I would imagine we should appear on it shortly.

**Comment by RyanNovas** [comment]
Have reapplied, Google should respond to hello account within 3 days.

**Comment by petergault** [comment]
@RyanNovas Can you confirm we are getting free google apps and then close this?
