### ISSUE TITLE
Sentence Shuffle Bug 

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Organization#72]
While using sentence shuffle, the check answer button seems to not be properly calculating scores. In this example below, the first and the final sentence are correct. However, the answer states 1/4 are correct. 

Perhaps this will be solved by doing the check answer by grouping clusters of sentences together that are correct.

![screen shot 2014-10-06 at 5 21 01 pm](https://cloud.githubusercontent.com/assets/3667179/4533994/346bb882-4da1-11e4-9b2d-6cb23ca7d35a.png)

**Comment by felipecocco** [comment]
This was originally the intended behavior - the point system just takes into account the relative position of the item. You get a point for the first paragraph, since it does indeed follow... the beginning. But the the last paragraph is not succeeding the second-to-last paragraph, so even though it is in its correct absolute position, its not considered correct.

In using this in a few classes, though, this proved to be absolutely horrible and unintuitive for students and teachers alike. I'm moving forward with the grouping of "correct" pairings of paragraphs, as well as changing the overall score to the absolute position of the paragraph. That should make the feedback be much more meaningful and helpful.

**Comment by petergault** [comment]
Cool, sounds great Felipe.

On Wed, Oct 8, 2014 at 8:43 PM, felipecocco notifications@github.com
wrote:

> This was originally the intended behavior - the point system just takes
> into account the relative position of the item. You get a point for the
> first paragraph, since it does indeed follow... the beginning. But the the
> last paragraph is not succeeding the second-to-last paragraph, so even
> though it is in its correct absolute position, its not considered correct.
> 
> In using this in a few classes, though, this proved to be absolutely
> horrible and unintuitive for students and teachers alike. I'm moving
> forward with the grouping of "correct" pairings of paragraphs, as well as
> changing the overall score to the absolute position of the paragraph. That
> should make the feedback be much more meaningful and helpful.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/empirical-org/organization/issues/72#issuecomment-58449494
> .

## 

Peter Gault
Quill Co-Founder and Product Director
http://quill.org

Learn more about Quill: http://youtu.be/BA6jaeberMg
